language: python
python: 2.7

before_install: sudo pip install -r requirements.txt
script: mkdocs build --clean

after_script: cp .travis.yaml site/

branches:
  only: sitecode

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: sitecode
  target_branch: master
  local_dir: site
  fqdn: docs.softfire.eu
