language: python
python: 2.7

sudo: false
cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install: pip install -r requirements.txt
script: mkdocs build --clean

branches:
  only: sitecode

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: sitecode
  target_branch: master
  local_dir: site
  fqdn: docs.softfire.eu
