site_name: SoftFIRE Software Documentation
pages:
- ['index.md', 'SoftFIRE', 'Introduction']
- ['wiki.md', 'Wiki', 'Getting Started']
- ['openvpnconfig.md', 'Extras', 'OpenVPN Manual configuration']

theme_dir: material
extra:
  palette:
    primary: 'deep orange'
    accent: 'orange'
repo_url: https://github.com/SoftFIRE-eu/experiment-manager
repo_name: SoftFIRE Experiment Manager
site_favicon: favicon.ico
markdown_extensions:
          - admonition
          - codehilite
          - footnotes
          - toc(permalink=true)
          - pymdownx.arithmatex
          - pymdownx.betterem(smart_enable=all)
          - pymdownx.caret
          - pymdownx.critic
          - pymdownx.emoji:
                    emoji_generator: !!python/name:pymdownx.emoji.to_svg
          - pymdownx.inlinehilite
          - pymdownx.magiclink
          - pymdownx.mark
          - pymdownx.smartsymbols
          - pymdownx.superfences
          - pymdownx.tasklist(custom_checkbox=true)
          - pymdownx.tilde

copyright: Copyright (c) 2016-2017 SoftFIRE (http://softfire.eu)
