site_name: SoftFIRE Documentation
pages:
- ['index.md', 'Get Started', 'SoftFIRE']
- ['wiki.md', 'Get Started', 'Wiki']

theme_dir: material/material
repo_url: https://github.com/SoftFIRE-eu
repo_name: SoftFIRE docs
site_favicon: favicon.ico
markdown_extensions:
          - admonition
          - codehilite
          - footnotes
          - toc(permalink=true)
          - pymdownx.arithmatex
          - pymdownx.betterem(smart_enable=all)
          - pymdownx.caret
          - pymdownx.critic
          - pymdownx.emoji:
                    emoji_generator: !!python/name:pymdownx.emoji.to_svg
          - pymdownx.inlinehilite
          - pymdownx.magiclink
          - pymdownx.mark
          - pymdownx.smartsymbols
          - pymdownx.superfences
          - pymdownx.tasklist(custom_checkbox=true)
          - pymdownx.tilde
extra_css:
          - 'stylesheets/extra.css'
copyright: Copyright (c) 2016-2017 SoftFIRE (http://softfire.eu)
